// Generated by CoffeeScript 1.3.1
(function() {
  var q;

  q = this.qiita;

  $(function() {
    return $('form').submit(function(e) {
      var password, url_name;
      url_name = $("#url_name").val();
      password = $("#password").val();
      $.when($.ajax({
        url: 'https://qiita.com/api/v1/auth',
        type: 'POST',
        data: {
          url_name: url_name,
          password: password
        },
        dataType: 'json'
      })).done(function(data) {
        var token;
        token = data.token;
        chrome.extension.sendRequest({
          action: 'settings',
          type: 'set',
          name: 'token',
          value: token
        });
        chrome.extension.sendRequest({
          action: 'settings',
          type: 'set',
          name: 'url_name',
          value: data.url_name
        });
        return location.href = 'options.html';
      }).fail(function() {
        return $('span').text('Authentication failed').show().fadeOut(5000);
      });
      return false;
    });
  });

}).call(this);
